services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5100:5100"
