services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
      - "5100:5100"
