services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    expose:
      - "5100"
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
