name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "VPS_HOST: $VPS_HOST"
          echo "VPS_USER: $VPS_USER"
          echo "VPS_SSH_KEY: ${VPS_SSH_KEY:+✅ Present}"
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
