name: Test SSH Login

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Try SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}  # should be root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: echo "✅ SSH login worked from GitHub Actions"
